package io.hrns_now.app.ui

import androidx.compose.runtime.staticCompositionLocalOf
import io.hrns_now.core.domain.model.AppLocale

/** 현재 화면 언어다(새 Phase 8 §7). 기본값은 한국어이며, `App()`이 `AppViewModel.locale`로 덮어쓴다. */
val LocalAppLocale = staticCompositionLocalOf { AppLocale.Korean }

/**
 * `infra`(`WorkspacePathProbe`)가 아직 typed 값이 아니라 고정된 한국어 단문으로 내는
 * `WorkspaceReadiness` 라벨/`PathProbeResult.message`를 위한, 닫힌 어휘 전용 번역표다(Phase 8
 * 보완 §1). 이 함수는 표시만 바꿀 뿐 어떤 분기·판단도 하지 않는다 — `infra`를 typed key로
 * 다시 설계하는 것은 이 Phase 범위를 넘는 대규모 변경이라 남겨 둔다(보고서 §3에 근거 기록).
 * 알려지지 않은 문자열은 원문 그대로 보존한다(원문 손실 방지).
 */
fun localizeInfraLabel(korean: String, locale: AppLocale): String {
    if (locale == AppLocale.Korean) return korean
    return when (korean) {
        "확인됨" -> "Confirmed"
        "미설정" -> "Not configured"
        "미선택" -> "Not selected"
        "미확인" -> "Not checked"
        "확인 필요" -> "Needs review"
        "읽기 가능" -> "Readable"
        "경로가 없습니다." -> "The path doesn't exist."
        "유형이 아닙니다." -> "Wrong type."
        "읽을 수 없습니다." -> "Can't be read."
        "경로 형식을 확인해야 합니다." -> "The path format needs review."
        "권한 확인이 필요합니다." -> "Permissions need review."
        "경로 상태를 확인해야 합니다." -> "The path status needs review."
        "명령 경로는 이후 상태 점검에서 확인합니다." -> "The command path is confirmed during a later status check."
        // WorkspaceArtifactProbe(infra)의 고정 artifact label 어휘.
        "요청 입력함" -> "Request inbox"
        "오늘 할 일 파일" -> "Today's plan file"
        "인수인계 파일" -> "Handoff file"
        "작업 상태 파일" -> "State file"
        "정리된 요청 파일" -> "Structured request file"
        "날짜 산출물 로그" -> "Daily output log"
        "래퍼 실행 로그" -> "Wrapper run log"
        "레거시 오늘 상태 파일" -> "Legacy today-state file"
        "레거시 작업 큐 파일" -> "Legacy work-queue file"
        else -> korean
    }
}

/**
 * 앱 상시 chrome(사이드바·상단 리본·알림함)의 정적 label 전용 locale catalog다(새 Phase 8 §7).
 * Setup/Cockpit/Strategy/Run/Recovery 화면 본문(각 projection이 조립하는 카드 제목·설명·버튼
 * 문구 다수)은 이 Phase에서 전부 번역하지 않았다 — 범위와 사유는 phase8 보고서에 남긴다.
 */
data class ChromeStrings(
    val navSectionWorkflow: String,
    val navSectionGuide: String,
    val navSetup: String,
    val navCockpit: String,
    val navStrategy: String,
    val navRun: String,
    val navRecovery: String,
    val readOnlyShellNote: String,
    val projectLabel: String,
    val notSelected: String,
    val readinessWorkspace: String,
    val readinessEngine: String,
    val readinessBridge: String,
    val readinessProfile: String,
    val readinessDoctor: String,
    val notificationBell: String,
    val notificationEmpty: String,
    val dismiss: String,
    val localeSelectorKorean: String,
    val localeSelectorEnglish: String,
    val inspectorHeading: String,
    val inspectorSubtitle: String,
    val artifactsEyebrow: String,
    val environmentEyebrow: String,
    val loadingNotice: String,
)

fun chromeStrings(locale: AppLocale): ChromeStrings =
    when (locale) {
        AppLocale.Korean -> ChromeStrings(
            navSectionWorkflow = "작업 흐름",
            navSectionGuide = "안내",
            navSetup = "프로젝트 관리",
            navCockpit = "작업 현황",
            navStrategy = "작업 계획",
            navRun = "실행 기록",
            navRecovery = "복구 센터 · 마감 확인",
            readOnlyShellNote = "작업공간 경로와 기준 파일 존재 여부만 읽는 read-only 셸입니다.",
            projectLabel = "프로젝트",
            notSelected = "선택 안 됨",
            readinessWorkspace = "작업공간",
            readinessEngine = "엔진",
            readinessBridge = "저장소",
            readinessProfile = "프로필",
            readinessDoctor = "점검",
            notificationBell = "알림",
            notificationEmpty = "최근 알림이 없습니다.",
            dismiss = "닫기",
            localeSelectorKorean = "한국어",
            localeSelectorEnglish = "English",
            inspectorHeading = "기준 파일",
            inspectorSubtitle = "워크스페이스 안에서 추적 중인 항목들",
            artifactsEyebrow = "기준 파일",
            environmentEyebrow = "환경",
            loadingNotice = "실데이터를 불러오는 중입니다…",
        )

        AppLocale.English -> ChromeStrings(
            navSectionWorkflow = "Workflow",
            navSectionGuide = "Guide",
            navSetup = "Project Setup",
            navCockpit = "Status",
            navStrategy = "Plan",
            navRun = "Run History",
            navRecovery = "Recovery · Closure",
            readOnlyShellNote = "A read-only shell that only reads the workspace path and whether required files exist.",
            projectLabel = "Project",
            notSelected = "Not selected",
            readinessWorkspace = "Workspace",
            readinessEngine = "Engine",
            readinessBridge = "Repository",
            readinessProfile = "Profile",
            readinessDoctor = "Doctor",
            notificationBell = "Notifications",
            notificationEmpty = "No recent notifications.",
            dismiss = "Dismiss",
            localeSelectorKorean = "한국어",
            localeSelectorEnglish = "English",
            inspectorHeading = "Reference files",
            inspectorSubtitle = "Items tracked inside the workspace",
            artifactsEyebrow = "Reference files",
            environmentEyebrow = "Environment",
            loadingNotice = "Loading real data…",
        )
    }

/**
 * Setup/Cockpit/Strategy/Run/Recovery 화면 본문·모달·버튼 전용 locale catalog다(Phase 8 보완 §1).
 * `ChromeStrings`가 다루던 상시 chrome 밖의, 각 화면이 직접 그리는 정적 문구를 모두 담는다 —
 * projection이 만드는 동적 값(상태 라벨 등)은 여전히 각 assembler가 locale을 받아 조립한다.
 * `Shell.kt`의 ARTIFACTS/ENVIRONMENT/INSPECTOR 패널 제목은 Phase 8에서 이미 "하나의 영문 표기
 * 규칙으로 통일"하기로 확정한 의도적 예외이므로 이 catalog에 포함하지 않는다.
 */
data class AppStrings(
    val actionsSectionTitle: String,
    val setup: SetupStrings,
    val cockpit: CockpitStrings,
    val strategy: StrategyStrings,
    val run: RunStrings,
    val recovery: RecoveryStrings,
    val requestEditor: RequestEditorStrings,
)

data class SetupStrings(
    val pathCheckTitle: String,
    val screenLanguageLabel: String,
    val activeProjectTitle: String,
    val noActiveProjectNotice: String,
    val staleLabel: String,
    val okLabel: String,
    val runtimeSourceRowLabel: String,
    val runtimeSourceProblemSuffix: String,
    val profileLabel: String,
    val workspaceRootLabel: String,
    val repositoryRootLabel: String,
    val notConfiguredLabel: String,
    val projectManagementTitle: String,
    val selectionBasisPrefix: String,
    val noProjectsNotice: String,
    val noActiveProjectSelectNotice: String,
    val activeLabel: String,
    val registerProjectButton: String,
    val registeredProjectsHeading: String,
    val selectButton: String,
    val deleteButton: String,
    val workspaceDaysTitle: String,
    val todayPrefix: String,
    val todayNotStartedNotice: String,
    val selectTodayDateButton: String,
    val noValidDayFoldersNotice: String,
    val readOnlyChip: String,
    val selectedChip: String,
    val openButton: String,
    val previousButton: String,
    val nextButton: String,
    val registrationFormTitle: String,
    val registrationFormHint: String,
    val displayNameLabel: String,
    val showAdvancedButton: String,
    val hideAdvancedButton: String,
    val useExternalKitLabel: String,
    val diagnosingButton: String,
    val diagnoseAndRegisterButton: String,
    val registrationRunningNotice: String,
    val registrationCompleteChip: String,
    val registrationFailedChip: String,
    val registeredNoticePrefix: String,
    val registeredNoticeSuffix: String,
)

data class CockpitStrings(
    val heroEyebrow: String,
    val titlePrefix: String,
    val staleChip: String,
    val readOnlyChip: String,
    val runtimeSourceCheckTitlePrefix: String,
    val compatibilityCheckTitle: String,
    val needsReviewTitle: String,
    val diagnosticsEyebrow: String,
    val stateTitle: String,
    val artifactsTitle: String,
    val nextActionTitle: String,
    /** 새 Phase 8 보완 §2.1: BootstrapDay가 primary일 때 실행 버튼 대신 보여줄 순수 navigation 버튼이다. */
    val goToPlanButton: String,
    val whatHappenedLabel: String,
    val lastKnownGoodLabel: String,
    val lastKnownGoodPreservedValue: String,
    val noneValue: String,
    val nextStepLabel: String,
    val profileLabel: String,
    val phaseLabel: String,
    val statusLabel: String,
    val queueStatusLabel: String,
    val activeCardLabel: String,
    val activeSliceLabel: String,
    val authorizedTargetLabel: String,
    val stopReasonLabel: String,
    val blockedReasonLabel: String,
    val opsValidationLabel: String,
    val closureLabel: String,
    val executionCompletedLabel: String,
    val lastSuccessfulReadLabel: String,
    val lastAttemptLabel: String,
)

data class StrategyStrings(
    val heroEyebrow: String,
    val requestSectionTitle: String,
    val requestSectionHint: String,
    val writeRequestButton: String,
    val requestEditingDisabledNotice: String,
    val developmentStrategyTitle: String,
    val pastRawChip: String,
    val rawChip: String,
    val noStrategyPastNotice: String,
    val noStrategyTodayNotice: String,
    val runningSuffix: String,
    val completedAtPrefix: String,
    val cancelRunButton: String,
    /** 새 Phase 8 보완 §2.1: Bootstrap 단일 CTA 카드 제목·설명이다. */
    val startWorkTitle: String,
    val startWorkExplanation: String,
    val blockedNoticeFallback: String,
)

data class RunStrings(
    val heroEyebrow: String,
    val detailTitle: String,
    val hideStagesButton: String,
    val showStagesButton: String,
    val consoleTitle: String,
    val stageDetailTitle: String,
    val failuresTitle: String,
    val cancelRunButton: String,
    val forceReleaseLockButton: String,
)

data class RecoveryStrings(
    val heroEyebrow: String,
    val activeCardEyebrow: String,
    val noIssueTitle: String,
    val noIssueNotice: String,
    val closureChecklistTitle: String,
    val acknowledgeIncompleteHandoffLabel: String,
    val readOnlyDiagnosticsTitle: String,
    val diagnosticsEyebrow: String,
    val continuityDiagnosticsLabel: String,
    val usageLedgerLabel: String,
    val failureHistoryLabel: String,
    val lastKnownGoodStateLabel: String,
    val compatibilityLabel: String,
    val lockLabel: String,
    val whatHappenedLabel: String,
    val preservedRecordLabel: String,
    val allowedNextActionLabel: String,
)

data class RequestEditorStrings(
    val modalTitle: String,
    val unsavedChangesPrompt: String,
    val continueEditingButton: String,
    val discardAndCloseButton: String,
    val hint: String,
    val titleFieldLabel: String,
    val typeLabel: String,
    val sourceLabel: String,
    val priorityLabel: String,
    val summaryFieldLabel: String,
    val detailFieldLabel: String,
    val constraintsFieldLabel: String,
    val savingNotice: String,
    val notAllowedNotice: String,
    val titleAndSummaryRequiredNotice: String,
    val savingButton: String,
    val saveButton: String,
)

fun appStrings(locale: AppLocale): AppStrings =
    when (locale) {
        AppLocale.Korean -> AppStrings(
            actionsSectionTitle = "실행 작업",
            setup = SetupStrings(
                pathCheckTitle = "경로 점검",
                screenLanguageLabel = "화면 언어",
                activeProjectTitle = "활성 프로젝트",
                noActiveProjectNotice = "선택된 프로젝트가 없습니다. 아래 프로젝트 관리에서 등록하거나 선택하세요.",
                staleLabel = "오래된 정보",
                okLabel = "정상",
                runtimeSourceRowLabel = "Runtime source",
                runtimeSourceProblemSuffix = "문제 있음",
                profileLabel = "프로필",
                workspaceRootLabel = "작업공간 경로",
                repositoryRootLabel = "저장소 경로",
                notConfiguredLabel = "미설정",
                projectManagementTitle = "프로젝트 관리",
                selectionBasisPrefix = "선택 근거:",
                noProjectsNotice = "등록된 프로젝트가 없습니다. 아래에서 새 프로젝트를 등록하세요.",
                noActiveProjectSelectNotice = "활성 프로젝트가 없습니다. 아래에서 프로젝트를 선택하세요.",
                activeLabel = "활성",
                registerProjectButton = "프로젝트 등록",
                registeredProjectsHeading = "등록된 프로젝트",
                selectButton = "선택",
                deleteButton = "삭제",
                workspaceDaysTitle = "작업 날짜",
                todayPrefix = "오늘 ·",
                todayNotStartedNotice = "아직 오늘 작업을 시작하지 않았습니다.",
                selectTodayDateButton = "오늘 날짜 선택",
                noValidDayFoldersNotice = "유효한 yyyy-MM-dd 날짜 폴더가 없습니다.",
                readOnlyChip = "읽기 전용",
                selectedChip = "선택됨",
                openButton = "열기",
                previousButton = "이전",
                nextButton = "다음",
                registrationFormTitle = "새 프로젝트 등록",
                registrationFormHint = "기본값은 개발용 내장 SDK(.local\\harness-kit)입니다. Kit 경로를 직접 입력할 필요가 없습니다.",
                displayNameLabel = "표시명",
                showAdvancedButton = "고급 설정",
                hideAdvancedButton = "고급 설정 숨기기",
                useExternalKitLabel = "외부 Harness Kit 사용",
                diagnosingButton = "진단 중…",
                diagnoseAndRegisterButton = "진단 후 등록",
                registrationRunningNotice = "연결 점검과 호환성을 확인하는 중입니다…",
                registrationCompleteChip = "등록 완료",
                registrationFailedChip = "등록 실패",
                registeredNoticePrefix = "'",
                registeredNoticeSuffix = "' 프로젝트를 등록했습니다.",
            ),
            cockpit = CockpitStrings(
                heroEyebrow = "작업 현황",
                titlePrefix = "작업 현황",
                staleChip = "오래된 정보",
                readOnlyChip = "읽기 전용",
                runtimeSourceCheckTitlePrefix = "Runtime source 확인",
                compatibilityCheckTitle = "Harness 호환성 확인",
                needsReviewTitle = "확인이 필요합니다",
                diagnosticsEyebrow = "상태 진단",
                stateTitle = "현재 상태",
                artifactsTitle = "기준 파일",
                nextActionTitle = "다음 작업",
                goToPlanButton = "작업 계획으로 이동",
                whatHappenedLabel = "최근 작업 기록",
                lastKnownGoodLabel = "마지막 정상 상태",
                lastKnownGoodPreservedValue = "보존됨 (아래는 마지막 정상 값입니다)",
                noneValue = "없음",
                nextStepLabel = "다음 작업",
                profileLabel = "프로필",
                phaseLabel = "작업 단계",
                statusLabel = "작업 상태",
                queueStatusLabel = "작업 대기열 상태",
                activeCardLabel = "현재 작업 카드",
                activeSliceLabel = "현재 작업 단위",
                authorizedTargetLabel = "허용된 대상 파일",
                stopReasonLabel = "중단 사유",
                blockedReasonLabel = "차단 사유",
                opsValidationLabel = "작업 기준 점검",
                closureLabel = "마감 상태",
                executionCompletedLabel = "실행 완료 여부",
                lastSuccessfulReadLabel = "마지막 정상 상태 읽기",
                lastAttemptLabel = "마지막 읽기 시도",
            ),
            strategy = StrategyStrings(
                heroEyebrow = "작업 계획",
                requestSectionTitle = "요구사항 작성",
                requestSectionHint = "오늘 해결할 문제, 기대 결과, 제약 조건을 적어 주세요. (저장 위치: REQUEST_INBOX.md · 구조화된 계획 입력은 REQUEST_STRUCTURED.md에서 별도로 다룹니다.)",
                writeRequestButton = "요구사항 작성",
                requestEditingDisabledNotice = "현재 날짜 또는 상태에서는 요구사항을 작성할 수 없습니다. 새로고침한 뒤 다시 확인하세요.",
                developmentStrategyTitle = "개발 전략",
                pastRawChip = "과거 날짜 · 원문",
                rawChip = "원문",
                noStrategyPastNotice = "이 날짜에는 작성된 개발 전략이 없습니다.",
                noStrategyTodayNotice = "아직 오늘의 개발 전략이 없습니다. 요구사항을 저장하고 계획을 생성하면 여기에 나타납니다.",
                runningSuffix = "진행 중입니다…",
                completedAtPrefix = "완료",
                cancelRunButton = "실행 취소",
                startWorkTitle = "오늘 작업 시작",
                startWorkExplanation = "오늘 날짜의 상태 파일이 아직 없습니다. \"오늘 작업 시작\"을 실행하면 상태 파일이 만들어지고, 그 결과에 따라 이 자리에 요구사항 작성이 열립니다.",
                blockedNoticeFallback = "현재 날짜 또는 상태에서는 요구사항을 작성할 수 없습니다. 새로고침한 뒤 다시 확인하세요.",
            ),
            run = RunStrings(
                heroEyebrow = "실행 기록",
                detailTitle = "실행 상세",
                hideStagesButton = "진행 단계 접기",
                showStagesButton = "진행 단계 보기",
                consoleTitle = "실행 로그",
                stageDetailTitle = "단계 상세",
                failuresTitle = "실패 유형",
                cancelRunButton = "실행 취소",
                forceReleaseLockButton = "잠금 강제 해제",
            ),
            recovery = RecoveryStrings(
                heroEyebrow = "복구 센터",
                activeCardEyebrow = "최근 작업 기록 · 보존된 기록 · 허용된 행동",
                noIssueTitle = "복구가 필요한 문제 없음",
                noIssueNotice = "현재 관측된 stop reason이나 queue blocked marker가 없습니다.",
                closureChecklistTitle = "마감 체크리스트",
                acknowledgeIncompleteHandoffLabel = "위 미완료 항목을 인지했으며 이 상태로 마감을 진행합니다.",
                readOnlyDiagnosticsTitle = "읽기 전용 진단",
                diagnosticsEyebrow = "상태 진단",
                continuityDiagnosticsLabel = "연속성 진단",
                usageLedgerLabel = "Usage ledger",
                failureHistoryLabel = "실패 이력",
                lastKnownGoodStateLabel = "마지막 정상 State",
                compatibilityLabel = "Harness 호환성",
                lockLabel = "잠금",
                whatHappenedLabel = "최근 작업 기록",
                preservedRecordLabel = "보존된 기록",
                allowedNextActionLabel = "현재 허용된 행동",
            ),
            requestEditor = RequestEditorStrings(
                modalTitle = "요구사항 작성",
                unsavedChangesPrompt = "저장하지 않은 변경사항이 있습니다. 닫으시겠습니까?",
                continueEditingButton = "계속 작성",
                discardAndCloseButton = "저장하지 않고 닫기",
                hint = "오늘 해결할 문제, 기대 결과, 제약 조건을 자유롭게 적어 주세요. 구조화된 계획 입력은 REQUEST_STRUCTURED.md에서 별도로 다룹니다.",
                titleFieldLabel = "제목",
                typeLabel = "유형",
                sourceLabel = "출처",
                priorityLabel = "우선순위",
                summaryFieldLabel = "요약",
                detailFieldLabel = "상세",
                constraintsFieldLabel = "제약",
                savingNotice = "저장 중입니다…",
                notAllowedNotice = "현재 날짜 또는 상태에서는 요구사항을 저장할 수 없습니다.",
                titleAndSummaryRequiredNotice = "제목과 요약을 입력하세요.",
                savingButton = "저장 중...",
                saveButton = "요구사항 저장",
            ),
        )

        AppLocale.English -> AppStrings(
            actionsSectionTitle = "Actions",
            setup = SetupStrings(
                pathCheckTitle = "Path check",
                screenLanguageLabel = "Screen language",
                activeProjectTitle = "Active project",
                noActiveProjectNotice = "No project is selected. Register or select one in project management below.",
                staleLabel = "Stale",
                okLabel = "OK",
                runtimeSourceRowLabel = "Runtime source",
                runtimeSourceProblemSuffix = "has a problem",
                profileLabel = "Profile",
                workspaceRootLabel = "Workspace root",
                repositoryRootLabel = "Repository root",
                notConfiguredLabel = "Not configured",
                projectManagementTitle = "Project management",
                selectionBasisPrefix = "Selection basis:",
                noProjectsNotice = "No projects are registered. Register a new project below.",
                noActiveProjectSelectNotice = "No active project. Select one below.",
                activeLabel = "Active",
                registerProjectButton = "Register project",
                registeredProjectsHeading = "Registered projects",
                selectButton = "Select",
                deleteButton = "Delete",
                workspaceDaysTitle = "Workspace days",
                todayPrefix = "Today ·",
                todayNotStartedNotice = "Today's work hasn't started yet.",
                selectTodayDateButton = "Select today's date",
                noValidDayFoldersNotice = "No valid yyyy-MM-dd date folders.",
                readOnlyChip = "Read-only",
                selectedChip = "Selected",
                openButton = "Open",
                previousButton = "Previous",
                nextButton = "Next",
                registrationFormTitle = "Register a new project",
                registrationFormHint = "The default is the internal developer SDK (.local\\harness-kit). You don't need to enter a Kit path yourself.",
                displayNameLabel = "Display name",
                showAdvancedButton = "Advanced settings",
                hideAdvancedButton = "Hide advanced settings",
                useExternalKitLabel = "Use an external Harness Kit",
                diagnosingButton = "Diagnosing…",
                diagnoseAndRegisterButton = "Diagnose and register",
                registrationRunningNotice = "Checking connection and compatibility…",
                registrationCompleteChip = "Registered",
                registrationFailedChip = "Registration failed",
                registeredNoticePrefix = "Registered project '",
                registeredNoticeSuffix = "'.",
            ),
            cockpit = CockpitStrings(
                heroEyebrow = "Status",
                titlePrefix = "Status",
                staleChip = "Stale",
                readOnlyChip = "Read-only",
                runtimeSourceCheckTitlePrefix = "Runtime source check",
                compatibilityCheckTitle = "Harness compatibility check",
                needsReviewTitle = "Needs review",
                diagnosticsEyebrow = "Diagnostics",
                stateTitle = "Current state",
                artifactsTitle = "Artifacts",
                nextActionTitle = "Next action",
                goToPlanButton = "Go to plan",
                whatHappenedLabel = "What happened",
                lastKnownGoodLabel = "Last known good state",
                lastKnownGoodPreservedValue = "Preserved (values below are the last known good)",
                noneValue = "None",
                nextStepLabel = "Next step",
                profileLabel = "Profile",
                phaseLabel = "Phase",
                statusLabel = "Status",
                queueStatusLabel = "Queue status",
                activeCardLabel = "Active card",
                activeSliceLabel = "Active slice",
                authorizedTargetLabel = "Authorized target file",
                stopReasonLabel = "Stop reason",
                blockedReasonLabel = "Blocked reason",
                opsValidationLabel = "Ops validation",
                closureLabel = "Closure status",
                executionCompletedLabel = "Execution completed",
                lastSuccessfulReadLabel = "Last successful read",
                lastAttemptLabel = "Last read attempt",
            ),
            strategy = StrategyStrings(
                heroEyebrow = "Plan",
                requestSectionTitle = "Write request",
                requestSectionHint = "Write the problem to solve today, the expected outcome, and any constraints. (Saved to REQUEST_INBOX.md · structured plan input is handled separately in REQUEST_STRUCTURED.md.)",
                writeRequestButton = "Write request",
                requestEditingDisabledNotice = "Requests can't be written in the current date or state. Refresh, then check again.",
                developmentStrategyTitle = "Development strategy",
                pastRawChip = "Past date · raw",
                rawChip = "Raw",
                noStrategyPastNotice = "No development strategy was written for this date.",
                noStrategyTodayNotice = "There's no development strategy for today yet. It will appear here once you save a request and generate a plan.",
                runningSuffix = "is in progress…",
                completedAtPrefix = "Completed",
                cancelRunButton = "Cancel run",
                startWorkTitle = "Start today's work",
                startWorkExplanation = "Today's state file doesn't exist yet. Running \"Start today's work\" creates the state file, and this spot then switches to writing a request based on the result.",
                blockedNoticeFallback = "Requests can't be written in the current date or state. Refresh, then check again.",
            ),
            run = RunStrings(
                heroEyebrow = "Run history",
                detailTitle = "Run details",
                hideStagesButton = "Hide stages",
                showStagesButton = "Show stages",
                consoleTitle = "Console log",
                stageDetailTitle = "Stage detail",
                failuresTitle = "Failure types",
                cancelRunButton = "Cancel run",
                forceReleaseLockButton = "Force-release lock",
            ),
            recovery = RecoveryStrings(
                heroEyebrow = "Recovery",
                activeCardEyebrow = "What happened · preserved record · allowed action",
                noIssueTitle = "No recovery issue",
                noIssueNotice = "No stop reason or queue blocked marker is currently observed.",
                closureChecklistTitle = "Closure checklist",
                acknowledgeIncompleteHandoffLabel = "I acknowledge the incomplete items above and want to close in this state.",
                readOnlyDiagnosticsTitle = "Read-only diagnostics",
                diagnosticsEyebrow = "Diagnostics",
                continuityDiagnosticsLabel = "Continuity diagnostics",
                usageLedgerLabel = "Usage ledger",
                failureHistoryLabel = "Failure history",
                lastKnownGoodStateLabel = "Last known good state",
                compatibilityLabel = "Harness compatibility",
                lockLabel = "Lock",
                whatHappenedLabel = "What happened",
                preservedRecordLabel = "Preserved record",
                allowedNextActionLabel = "Currently allowed action",
            ),
            requestEditor = RequestEditorStrings(
                modalTitle = "Write request",
                unsavedChangesPrompt = "You have unsaved changes. Close anyway?",
                continueEditingButton = "Keep editing",
                discardAndCloseButton = "Close without saving",
                hint = "Freely write the problem to solve today, the expected outcome, and any constraints. Structured plan input is handled separately in REQUEST_STRUCTURED.md.",
                titleFieldLabel = "Title",
                typeLabel = "Type",
                sourceLabel = "Source",
                priorityLabel = "Priority",
                summaryFieldLabel = "Summary",
                detailFieldLabel = "Detail",
                constraintsFieldLabel = "Constraints",
                savingNotice = "Saving…",
                notAllowedNotice = "Requests can't be saved in the current date or state.",
                titleAndSummaryRequiredNotice = "Enter a title and summary.",
                savingButton = "Saving...",
                saveButton = "Save request",
            ),
        )
    }
